import { Box, AppBar, Toolbar, Typography, Stack } from '@mui/material'
import Button from '../components/Button'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Box display="flex" flexGrow={1}>
        <AppBar position="static">
          <Toolbar>
            <Typography
              variant="h6"
              component="div"
              display="flex"
              flexGrow={1}
            >
              Logo
            </Typography>
            <Button color="inherit">Login</Button>
            <Button color="inherit">Register</Button>
          </Toolbar>
        </AppBar>
      </Box>
      <Stack
        direction={{ xs: 'column', sm: 'row' }}
        spacing={{ xs: 1, sm: 2, md: 4 }}
        useFlexGap
        flexWrap="wrap"
        justifyContent="center"
        alignItems="center"
        mt={3}
      >
        {children}
      </Stack>
    </>
  )
}
